/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formatriangulo;

/**
 *
 * @author gabri
 */
public class TelaTriangulo extends javax.swing.JFrame {

    /**
     * Creates new form TelaTriangulo
     */
    public TelaTriangulo() {
        initComponents();
        equilatero.setVisible(false);
        isoceles.setVisible(false);
        escaleno.setVisible(false);
        painel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sliA = new javax.swing.JSlider();
        sliB = new javax.swing.JSlider();
        sliC = new javax.swing.JSlider();
        lblA = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        lblC = new javax.swing.JLabel();
        escaleno = new javax.swing.JLabel();
        equilatero = new javax.swing.JLabel();
        isoceles = new javax.swing.JLabel();
        btnVer = new javax.swing.JButton();
        painel = new javax.swing.JPanel();
        lblRes = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Segmento a");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 53, -1, -1));

        jLabel2.setText("Segmento b");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 91, -1, -1));

        jLabel3.setText("Segmento c");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 127, -1, -1));

        sliA.setMaximum(20);
        sliA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliAStateChanged(evt);
            }
        });
        getContentPane().add(sliA, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 52, 123, -1));

        sliB.setMaximum(20);
        sliB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliBStateChanged(evt);
            }
        });
        getContentPane().add(sliB, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 90, 123, -1));

        sliC.setMaximum(20);
        sliC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliCStateChanged(evt);
            }
        });
        getContentPane().add(sliC, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 126, 123, -1));

        lblA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblA.setForeground(new java.awt.Color(153, 153, 153));
        lblA.setText("0");
        getContentPane().add(lblA, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        lblB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblB.setForeground(new java.awt.Color(153, 153, 153));
        lblB.setText("0");
        getContentPane().add(lblB, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        lblC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblC.setForeground(new java.awt.Color(153, 153, 153));
        lblC.setText("0");
        getContentPane().add(lblC, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        escaleno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formatriangulo/escaleno.png"))); // NOI18N
        getContentPane().add(escaleno, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, -30, -1, -1));

        equilatero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formatriangulo/equilatero.png"))); // NOI18N
        getContentPane().add(equilatero, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 210, 200));

        isoceles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formatriangulo/isoceles.png"))); // NOI18N
        getContentPane().add(isoceles, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 180, 220));

        btnVer.setText("Verificar");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        getContentPane().add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 90, 40));

        lblRes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblRes.setForeground(new java.awt.Color(51, 51, 255));
        lblRes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRes.setText("Forma um triângulo");
        lblRes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        painel.add(lblRes);

        lblTipo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(255, 51, 51));
        lblTipo.setText("Tipo de Triângulo");
        lblTipo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        painel.add(lblTipo);

        getContentPane().add(painel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 310, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
        painel.setVisible(true);
        int a  = sliA.getValue();
        int b = sliB.getValue();
        int c = sliC.getValue();
        
        // CONDICAO P/ FORMAR UM TRIANGULO
        if ((a + c > b) || (a + b < c)||(a + b < c)) {
            lblRes.setText("Forma um Triângulo !");
            lblTipo.setVisible(true);
              // TIPO DO TRIANGULO
            if ((a == b) && (b == c)) {
               escaleno.setVisible(false);
               isoceles.setVisible(false);
               lblTipo.setText("Equilátero");
               equilatero.setVisible(true);
                
            } else if ((a!=b) && (b!=c)){
                isoceles.setVisible(false);
                equilatero.setVisible(false);
                lblTipo.setText("Escaleno");
                escaleno.setVisible(true);
            } else {
                escaleno.setVisible(false);
                equilatero.setVisible(false);
                lblTipo.setText("Isóceles");
                isoceles.setVisible(true);
            }
            
        } else {
            lblRes.setText("Não forma um Triângulo");
            lblTipo.setVisible(false);
            escaleno.setVisible(false);
            isoceles.setVisible(false);
            equilatero.setVisible(true);
        }
        
   
    }//GEN-LAST:event_btnVerActionPerformed

    private void sliAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliAStateChanged
        // TODO add your handling code here:
        lblA.setText(Integer.toString(sliA.getValue()));
    }//GEN-LAST:event_sliAStateChanged

    private void sliBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliBStateChanged
        // TODO add your handling code here:
        lblB.setText(Integer.toString(sliB.getValue()));
    }//GEN-LAST:event_sliBStateChanged

    private void sliCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliCStateChanged
        // TODO add your handling code here:
        lblC.setText(Integer.toString(sliC.getValue()));
    }//GEN-LAST:event_sliCStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTriangulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVer;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel equilatero;
    private javax.swing.JLabel escaleno;
    private javax.swing.JLabel isoceles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblRes;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JPanel painel;
    private javax.swing.JSlider sliA;
    private javax.swing.JSlider sliB;
    private javax.swing.JSlider sliC;
    // End of variables declaration//GEN-END:variables
}
